### PR TITLE
fix: map timestamp correctly, add "queryDocuments"

### LINKED ISSUE #2: Receiving a Document with a field type of "timstamp" crashes the app.
Timestamp field crashes the app when you get a document.  Is this a non-js-bridgable type?

```
-[FIRTimestamp boundBridge:withKrollObject:]: unrecognized selector sent to instance 0x600004f11c00
[INFO]  *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[FIRTimestamp boundBridge:withKrollObject:]: unrecognized selector sent to instance 0x600004f11c00'
```

### PR DESCRIPTION
**Pull request by hansemannn**
Fixes https://github.com/hansemannn/titanium-firebase-firestore/issues/2

Please verify before it can be merged!

### CODE REVIEW

File: ios/Classes/FirebaseFirestoreModule.m [hunk 1]
```diff
@@ -34,13 +35,84 @@ - (void)addDocument:(id)params
...
+    query = [ref queryWhereField:field in:filters];
+  } else if ([opStr isEqualToString:@"array-contains"]) {
+    query = [ref queryWhereField:field arrayContains:filters];
+  } else if ([opStr isEqualToString:@"array-contains-any"]) {
+    query = [ref queryWhereField:field arrayContainsAny:filters];
+  } else {
+    NSLog(@"[ERROR] Unknown operator type \"%@\"", opStr);
+  }
+
+  [[FIRFirestore.firestore collectionWithPath:collection] getDocumentsWithCompletion:^(FIRQuerySnapshot *_Nullable snapshot, NSError *_Nullable error) {
```
Comment (greatschism) [inline ios/Classes/FirebaseFirestoreModule.m]: Should it be changed to query
